function love.conf(t)
    t.identity = save                    -- The name of the save directory (string)
    t.version = "11.0"                   -- The LÖVE version this game was made for (string)
    t.gammacorrect = true                -- Enable gamma-correct rendering, when supported by the system (boolean)
    t.audio.mixwithsystem = false        -- Keep background music playing when opening LOVE (boolean, iOS and Android only)
    t.window.title = "Generator"         -- The window title (string)
    t.window.icon = nil                  -- Filepath to an image to use as the window's icon (string)
    t.window.width = 800                 -- The window width (number)
    t.window.height = 800                -- The window height (number)
    t.window.borderless = false           -- Remove all border visuals from the window (boolean)
    t.window.resizable = true            -- Let the window be user-resizable (boolean)
    t.window.minwidth = 800              -- Minimum window width if the window is resizable (number)
    t.window.minheight = 600             -- Minimum window height if the window is resizable (number)
    t.window.msaa = 2                   -- The number of samples to use with multi-sampled antialiasing (number)
end